import type { Metadata } from "next";
import {  Inter } from "next/font/google";
import '@ant-design/v5-patch-for-react-19';
import "./globals.css";
import ToastProvider from "./lib/ToastProvider";
import AntdPatchLoader from "./components/AntdPatchLoader";

const inter = Inter({
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
   <body className={`${inter.className} antialiased`}>
        <AntdPatchLoader />
        <ToastProvider />
          {children}
      </body>
    </html>
  );
}
